/** Generated by scripts/align-narration.py. Continuous Irodori masters. */
export type NarrationVoice = "female" | "male";
export interface NarrationCue { text: string; start: number; end: number; safeEnd?: boolean }
export interface NarrationClip {
  passageId: string; voice: NarrationVoice; url: string; duration: number;
  sampleRate: number; cues: readonly NarrationCue[]; sha256: string;
}
// Immutable asset commit; changed only after audio-assets has been committed.
export const NARRATION_ASSET_REVISION = "d1c94eb1e6d34790540bddbe5365baca5ed55233";
export const NARRATION_ASSET_BASE_URL = `https://raw.githubusercontent.com/ivgtr/puzzroaozora/${NARRATION_ASSET_REVISION}/audio-assets/masters`;
export const NARRATION: Readonly<Record<string, Readonly<Record<NarrationVoice, NarrationClip>>>> = {
"lemon-opening-v4": {
"female": {
  "passageId": "lemon-opening-v4",
  "voice": "female",
  "duration": 20.32,
  "sampleRate": 48000,
  "sha256": "dd833a9a6eb559ff19a05467e09e1653ae966be1286d39c9331a24ae79c5220a",
  "cues": [
    {
      "text": "えたいの知れない不吉な塊が",
      "start": 0.0,
      "end": 2.58,
      "safeEnd": true
    },
    {
      "text": "私の心を始終圧えつけていた。",
      "start": 2.58,
      "end": 5.928,
      "safeEnd": true
    },
    {
      "text": "焦躁と言おうか、",
      "start": 5.928,
      "end": 7.872,
      "safeEnd": true
    },
    {
      "text": "嫌悪と言おうか――",
      "start": 7.872,
      "end": 9.552,
      "safeEnd": true
    },
    {
      "text": "酒を飲んだあとに宿酔があるように、",
      "start": 9.552,
      "end": 13.002,
      "safeEnd": true
    },
    {
      "text": "酒を毎日飲んでいると",
      "start": 13.002,
      "end": 15.2,
      "safeEnd": true
    },
    {
      "text": "宿酔に相当した時期がやって来る。",
      "start": 15.2,
      "end": 18.352,
      "safeEnd": true
    },
    {
      "text": "それが来たのだ。",
      "start": 18.352,
      "end": 20.32,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-opening-v4-female.wav`
},
"male": {
  "passageId": "lemon-opening-v4",
  "voice": "male",
  "duration": 19.56,
  "sampleRate": 48000,
  "sha256": "5fb0a3050933fcdf783e9f5a97dbf2bdd3075ebb0d13612ccb91dc199b56fdb1",
  "cues": [
    {
      "text": "えたいの知れない不吉な塊が",
      "start": 0.0,
      "end": 2.548,
      "safeEnd": true
    },
    {
      "text": "私の心を始終圧えつけていた。",
      "start": 2.548,
      "end": 5.996,
      "safeEnd": true
    },
    {
      "text": "焦躁と言おうか、",
      "start": 5.996,
      "end": 8.136,
      "safeEnd": true
    },
    {
      "text": "嫌悪と言おうか――",
      "start": 8.136,
      "end": 9.85,
      "safeEnd": true
    },
    {
      "text": "酒を飲んだあとに宿酔があるように、",
      "start": 9.85,
      "end": 12.912,
      "safeEnd": true
    },
    {
      "text": "酒を毎日飲んでいると",
      "start": 12.912,
      "end": 14.948,
      "safeEnd": true
    },
    {
      "text": "宿酔に相当した時期がやって来る。",
      "start": 14.948,
      "end": 17.812,
      "safeEnd": true
    },
    {
      "text": "それが来たのだ。",
      "start": 17.812,
      "end": 19.56,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-opening-v4-male.wav`
}
},
"cat-palm-v4": {
"female": {
  "passageId": "cat-palm-v4",
  "voice": "female",
  "duration": 18.6,
  "sampleRate": 48000,
  "sha256": "1222d270d4dec815198f41abd9ed73fe76382a4080ea5952c2e159936f1f2791",
  "cues": [
    {
      "text": "この書生の掌の裏で",
      "start": 0.0,
      "end": 2.226,
      "safeEnd": true
    },
    {
      "text": "しばらくはよい心持に坐っておったが、",
      "start": 2.226,
      "end": 5.568,
      "safeEnd": true
    },
    {
      "text": "しばらくすると",
      "start": 5.568,
      "end": 7.072,
      "safeEnd": true
    },
    {
      "text": "非常な速力で運転し始めた。",
      "start": 7.072,
      "end": 10.118,
      "safeEnd": true
    },
    {
      "text": "書生が動くのか自分だけが動くのか分らないが",
      "start": 10.118,
      "end": 14.702,
      "safeEnd": true
    },
    {
      "text": "無暗に眼が廻る。",
      "start": 14.702,
      "end": 16.714,
      "safeEnd": true
    },
    {
      "text": "胸が悪くなる。",
      "start": 16.714,
      "end": 18.6,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/cat-palm-v4-female.wav`
},
"male": {
  "passageId": "cat-palm-v4",
  "voice": "male",
  "duration": 18.32,
  "sampleRate": 48000,
  "sha256": "8888fefa11d61a4743c2b7c81d9741bab986d001216e26d5a25d84083ed7a876",
  "cues": [
    {
      "text": "この書生の掌の裏で",
      "start": 0.0,
      "end": 2.204,
      "safeEnd": true
    },
    {
      "text": "しばらくはよい心持に坐っておったが、",
      "start": 2.204,
      "end": 5.572,
      "safeEnd": true
    },
    {
      "text": "しばらくすると",
      "start": 5.572,
      "end": 7.182,
      "safeEnd": true
    },
    {
      "text": "非常な速力で運転し始めた。",
      "start": 7.182,
      "end": 10.14,
      "safeEnd": true
    },
    {
      "text": "書生が動くのか自分だけが動くのか分らないが",
      "start": 10.14,
      "end": 14.206,
      "safeEnd": true
    },
    {
      "text": "無暗に眼が廻る。",
      "start": 14.206,
      "end": 16.374,
      "safeEnd": true
    },
    {
      "text": "胸が悪くなる。",
      "start": 16.374,
      "end": 18.32,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/cat-palm-v4-male.wav`
}
},
"cat-pond-v4": {
"female": {
  "passageId": "cat-pond-v4",
  "voice": "female",
  "duration": 21.48,
  "sampleRate": 48000,
  "sha256": "f58b19c996a930dd715655ba19fe0d3674a4f13cea01377c165644c2502a16d9",
  "cues": [
    {
      "text": "しばらくして泣いたら書生がまた迎に来てくれるかと考え付いた。",
      "start": 0.0,
      "end": 5.262,
      "safeEnd": true
    },
    {
      "text": "ニャー、ニャーと試みにやって見たが",
      "start": 5.262,
      "end": 8.772,
      "safeEnd": true
    },
    {
      "text": "誰も来ない。",
      "start": 8.772,
      "end": 10.22,
      "safeEnd": true
    },
    {
      "text": "そのうち池の上をさらさらと風が渡って日が暮れかかる。",
      "start": 10.22,
      "end": 16.096,
      "safeEnd": true
    },
    {
      "text": "腹が非常に減って来た。",
      "start": 16.096,
      "end": 18.86,
      "safeEnd": true
    },
    {
      "text": "泣きたくても声が出ない。",
      "start": 18.86,
      "end": 21.48,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/cat-pond-v4-female.wav`
},
"male": {
  "passageId": "cat-pond-v4",
  "voice": "male",
  "duration": 20.56,
  "sampleRate": 48000,
  "sha256": "a14e97d917c0e26d6515ff9839d20b068b76aa1da6002ede17e77a95a9e31980",
  "cues": [
    {
      "text": "しばらくして泣いたら書生がまた迎に来てくれるかと考え付いた。",
      "start": 0.0,
      "end": 4.668,
      "safeEnd": true
    },
    {
      "text": "ニャー、ニャーと試みにやって見たが",
      "start": 4.668,
      "end": 8.774,
      "safeEnd": true
    },
    {
      "text": "誰も来ない。",
      "start": 8.774,
      "end": 10.536,
      "safeEnd": true
    },
    {
      "text": "そのうち池の上をさらさらと風が渡って日が暮れかかる。",
      "start": 10.536,
      "end": 15.588,
      "safeEnd": true
    },
    {
      "text": "腹が非常に減って来た。",
      "start": 15.588,
      "end": 18.14,
      "safeEnd": true
    },
    {
      "text": "泣きたくても声が出ない。",
      "start": 18.14,
      "end": 20.56,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/cat-pond-v4-male.wav`
}
},
"cat-home-v4": {
"female": {
  "passageId": "cat-home-v4",
  "voice": "female",
  "duration": 17.32,
  "sampleRate": 48000,
  "sha256": "7be44d3f5ce31f594a52a4ba5ce9d7514c7596a8d85ff0158309e05fe4ad5198",
  "cues": [
    {
      "text": "主人は",
      "start": 0.0,
      "end": 0.994,
      "safeEnd": true
    },
    {
      "text": "鼻の下の黒い毛を撚りながら",
      "start": 0.994,
      "end": 3.618,
      "safeEnd": true
    },
    {
      "text": "吾輩の顔をしばらく眺めておったが、",
      "start": 3.618,
      "end": 6.734,
      "safeEnd": true
    },
    {
      "text": "やがてそんなら",
      "start": 6.734,
      "end": 9.286,
      "safeEnd": true
    },
    {
      "text": "内へ置いてやれといったまま",
      "start": 9.286,
      "end": 11.378,
      "safeEnd": true
    },
    {
      "text": "奥へ這入ってしまった。",
      "start": 11.378,
      "end": 13.466,
      "safeEnd": true
    },
    {
      "text": "主人はあまり口を聞かぬ人と見えた。",
      "start": 13.466,
      "end": 17.32,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/cat-home-v4-female.wav`
},
"male": {
  "passageId": "cat-home-v4",
  "voice": "male",
  "duration": 16.88,
  "sampleRate": 48000,
  "sha256": "3f0fbee29039d1ccf9aa7ee58d511c4fea0b4caa93a30be060edaac226bea7b5",
  "cues": [
    {
      "text": "主人は",
      "start": 0.0,
      "end": 0.94,
      "safeEnd": true
    },
    {
      "text": "鼻の下の黒い毛を撚りながら",
      "start": 0.94,
      "end": 3.476,
      "safeEnd": true
    },
    {
      "text": "吾輩の顔をしばらく眺めておったが、",
      "start": 3.476,
      "end": 6.612,
      "safeEnd": true
    },
    {
      "text": "やがてそんなら",
      "start": 6.612,
      "end": 8.748,
      "safeEnd": true
    },
    {
      "text": "内へ置いてやれといったまま",
      "start": 8.748,
      "end": 11.048,
      "safeEnd": true
    },
    {
      "text": "奥へ這入ってしまった。",
      "start": 11.048,
      "end": 13.462,
      "safeEnd": true
    },
    {
      "text": "主人はあまり口を聞かぬ人と見えた。",
      "start": 13.462,
      "end": 16.88,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/cat-home-v4-male.wav`
}
},
"cat-study-v4": {
"female": {
  "passageId": "cat-study-v4",
  "voice": "female",
  "duration": 16.68,
  "sampleRate": 48000,
  "sha256": "114ba8cc6f5147e9ff6e9dafbda18e599767502d8bd46b78540ca9f4021122c9",
  "cues": [
    {
      "text": "大飯を食った後で",
      "start": 0.0,
      "end": 1.678,
      "safeEnd": true
    },
    {
      "text": "タカジヤスターゼを飲む。",
      "start": 1.678,
      "end": 3.596,
      "safeEnd": true
    },
    {
      "text": "飲んだ後で",
      "start": 3.596,
      "end": 4.992,
      "safeEnd": true
    },
    {
      "text": "書物をひろげる。",
      "start": 4.992,
      "end": 6.704,
      "safeEnd": true
    },
    {
      "text": "二三ページ読むと",
      "start": 6.704,
      "end": 8.546,
      "safeEnd": true
    },
    {
      "text": "眠くなる。",
      "start": 8.546,
      "end": 9.984,
      "safeEnd": true
    },
    {
      "text": "涎を本の上へ垂らす。",
      "start": 9.984,
      "end": 12.774,
      "safeEnd": true
    },
    {
      "text": "これが彼の毎夜繰り返す日課である。",
      "start": 12.774,
      "end": 16.68,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/cat-study-v4-female.wav`
},
"male": {
  "passageId": "cat-study-v4",
  "voice": "male",
  "duration": 16.72,
  "sampleRate": 48000,
  "sha256": "c34f5fdc742707568c6c02f1d39af631a3f0e92f98dddf6f8da6ad1b50e426f5",
  "cues": [
    {
      "text": "大飯を食った後で",
      "start": 0.0,
      "end": 1.672,
      "safeEnd": true
    },
    {
      "text": "タカジヤスターゼを飲む。",
      "start": 1.672,
      "end": 3.708,
      "safeEnd": true
    },
    {
      "text": "飲んだ後で",
      "start": 3.708,
      "end": 5.18,
      "safeEnd": true
    },
    {
      "text": "書物をひろげる。",
      "start": 5.18,
      "end": 7.07,
      "safeEnd": true
    },
    {
      "text": "二三ページ読むと",
      "start": 7.07,
      "end": 8.938,
      "safeEnd": true
    },
    {
      "text": "眠くなる。",
      "start": 8.938,
      "end": 10.424,
      "safeEnd": true
    },
    {
      "text": "涎を本の上へ垂らす。",
      "start": 10.424,
      "end": 13.306,
      "safeEnd": true
    },
    {
      "text": "これが彼の毎夜繰り返す日課である。",
      "start": 13.306,
      "end": 16.72,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/cat-study-v4-male.wav`
}
},
"lemon-shop-v4": {
"female": {
  "passageId": "lemon-shop-v4",
  "voice": "female",
  "duration": 18.76,
  "sampleRate": 48000,
  "sha256": "c8c0a4c203a0e277d9cd46b3d4a9cc53c00ec93e77c91b0f57fadfa6d56625a2",
  "cues": [
    {
      "text": "いったい私は",
      "start": 0.0,
      "end": 1.436,
      "safeEnd": true
    },
    {
      "text": "あの檸檬が好きだ。",
      "start": 1.436,
      "end": 3.498,
      "safeEnd": true
    },
    {
      "text": "レモンエロウの絵具をチューブから搾り出して",
      "start": 3.498,
      "end": 6.902,
      "safeEnd": true
    },
    {
      "text": "固めたようなあの単純な色も、",
      "start": 6.902,
      "end": 9.576,
      "safeEnd": true
    },
    {
      "text": "それからあの丈の詰まった紡錘形の恰好も。――",
      "start": 9.576,
      "end": 14.378,
      "safeEnd": true
    },
    {
      "text": "結局私はそれを一つだけ買うことにした。",
      "start": 14.378,
      "end": 18.76,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-shop-v4-female.wav`
},
"male": {
  "passageId": "lemon-shop-v4",
  "voice": "male",
  "duration": 17.92,
  "sampleRate": 48000,
  "sha256": "c10c97322b527136e678f91dc7730588998ca8ddf329bdd3ba28d230fc767ba7",
  "cues": [
    {
      "text": "いったい私は",
      "start": 0.0,
      "end": 1.4,
      "safeEnd": true
    },
    {
      "text": "あの檸檬が好きだ。",
      "start": 1.4,
      "end": 3.596,
      "safeEnd": true
    },
    {
      "text": "レモンエロウの絵具をチューブから搾り出して",
      "start": 3.596,
      "end": 7.08,
      "safeEnd": true
    },
    {
      "text": "固めたようなあの単純な色も、",
      "start": 7.08,
      "end": 9.938,
      "safeEnd": true
    },
    {
      "text": "それからあの丈の詰まった紡錘形の恰好も。――",
      "start": 9.938,
      "end": 14.214,
      "safeEnd": true
    },
    {
      "text": "結局私はそれを一つだけ買うことにした。",
      "start": 14.214,
      "end": 17.92,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-shop-v4-male.wav`
}
},
"lemon-coolness-v4": {
"female": {
  "passageId": "lemon-coolness-v4",
  "voice": "female",
  "duration": 21.56,
  "sampleRate": 48000,
  "sha256": "388e9ea94e5b3b4d7c641e3d67537ed83d46691b0dd75ea9936cd64b34aae373",
  "cues": [
    {
      "text": "事実友達の誰彼に",
      "start": 0.0,
      "end": 2.208,
      "safeEnd": true
    },
    {
      "text": "私の熱を見せびらかすために",
      "start": 2.208,
      "end": 4.78,
      "safeEnd": true
    },
    {
      "text": "手の握り合いなどをしてみるのだが、",
      "start": 4.78,
      "end": 7.672,
      "safeEnd": true
    },
    {
      "text": "私の掌が誰のよりも熱かった。",
      "start": 7.672,
      "end": 11.75,
      "safeEnd": true
    },
    {
      "text": "その熱い故だったのだろう、",
      "start": 11.75,
      "end": 14.434,
      "safeEnd": true
    },
    {
      "text": "握っている掌から",
      "start": 14.434,
      "end": 16.458,
      "safeEnd": true
    },
    {
      "text": "身内に浸み透ってゆくようなその冷たさは",
      "start": 16.458,
      "end": 19.792,
      "safeEnd": true
    },
    {
      "text": "快いものだった。",
      "start": 19.792,
      "end": 21.56,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-coolness-v4-female.wav`
},
"male": {
  "passageId": "lemon-coolness-v4",
  "voice": "male",
  "duration": 21.32,
  "sampleRate": 48000,
  "sha256": "0f77e205e85d08b5d5cf78b49e77348e80a72f167f405c1af97b5cd5544c3be4",
  "cues": [
    {
      "text": "事実友達の誰彼に",
      "start": 0.0,
      "end": 2.238,
      "safeEnd": true
    },
    {
      "text": "私の熱を見せびらかすために",
      "start": 2.238,
      "end": 4.776,
      "safeEnd": true
    },
    {
      "text": "手の握り合いなどをしてみるのだが、",
      "start": 4.776,
      "end": 7.516,
      "safeEnd": true
    },
    {
      "text": "私の掌が誰のよりも熱かった。",
      "start": 7.516,
      "end": 11.69,
      "safeEnd": true
    },
    {
      "text": "その熱い故だったのだろう、",
      "start": 11.69,
      "end": 14.272,
      "safeEnd": true
    },
    {
      "text": "握っている掌から",
      "start": 14.272,
      "end": 16.182,
      "safeEnd": true
    },
    {
      "text": "身内に浸み透ってゆくようなその冷たさは",
      "start": 16.182,
      "end": 19.392,
      "safeEnd": true
    },
    {
      "text": "快いものだった。",
      "start": 19.392,
      "end": 21.32,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-coolness-v4-male.wav`
}
},
"lemon-fragrance-v4": {
"female": {
  "passageId": "lemon-fragrance-v4",
  "voice": "female",
  "duration": 20.6,
  "sampleRate": 48000,
  "sha256": "4885b0c7f44c25116220b8c77eb85a31ec4bb5c49d008b29914091187ec750c8",
  "cues": [
    {
      "text": "私は何度も何度も",
      "start": 0.0,
      "end": 2.108,
      "safeEnd": true
    },
    {
      "text": "その果実を鼻に持っていっては",
      "start": 2.108,
      "end": 4.674,
      "safeEnd": true
    },
    {
      "text": "嗅いでみた。",
      "start": 4.674,
      "end": 6.038,
      "safeEnd": true
    },
    {
      "text": "それの産地だというカリフォルニヤが想像に上って来る。",
      "start": 6.038,
      "end": 10.708,
      "safeEnd": true
    },
    {
      "text": "漢文で習った「売柑者之言」の中に書いてあった「鼻を撲つ」という言葉が",
      "start": 10.708,
      "end": 18.72,
      "safeEnd": true
    },
    {
      "text": "断れぎれに浮かんで来る。",
      "start": 18.72,
      "end": 20.6,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-fragrance-v4-female.wav`
},
"male": {
  "passageId": "lemon-fragrance-v4",
  "voice": "male",
  "duration": 20.4,
  "sampleRate": 48000,
  "sha256": "317a8b70ca45e37086198ae37b05056b4b18b0104170388a3cd5e2dda19b981b",
  "cues": [
    {
      "text": "私は何度も何度も",
      "start": 0.0,
      "end": 1.912,
      "safeEnd": true
    },
    {
      "text": "その果実を鼻に持っていっては",
      "start": 1.912,
      "end": 4.25,
      "safeEnd": true
    },
    {
      "text": "嗅いでみた。",
      "start": 4.25,
      "end": 5.64,
      "safeEnd": true
    },
    {
      "text": "それの産地だというカリフォルニヤが想像に上って来る。",
      "start": 5.64,
      "end": 10.394,
      "safeEnd": true
    },
    {
      "text": "漢文で習った「売柑者之言」の中に書いてあった「鼻を撲つ」という言葉が",
      "start": 10.394,
      "end": 18.354,
      "safeEnd": true
    },
    {
      "text": "断れぎれに浮かんで来る。",
      "start": 18.354,
      "end": 20.4,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-fragrance-v4-male.wav`
}
},
"lemon-street-v4": {
"female": {
  "passageId": "lemon-street-v4",
  "voice": "female",
  "duration": 20.88,
  "sampleRate": 48000,
  "sha256": "b6ec9aa234984fccf03cd05e29ce1cab75a78dd3a12d52d78ac4524f2c4f94c1",
  "cues": [
    {
      "text": "雨や風が蝕んで",
      "start": 0.0,
      "end": 1.942,
      "safeEnd": true
    },
    {
      "text": "やがて土に帰ってしまう、",
      "start": 1.942,
      "end": 4.108,
      "safeEnd": true
    },
    {
      "text": "と言ったような趣きのある街で、",
      "start": 4.108,
      "end": 6.818,
      "safeEnd": true
    },
    {
      "text": "土塀が崩れていたり",
      "start": 6.818,
      "end": 8.84,
      "safeEnd": true
    },
    {
      "text": "家並が傾きかかっていたり――",
      "start": 8.84,
      "end": 11.514,
      "safeEnd": true
    },
    {
      "text": "勢いのいいのは植物だけで、",
      "start": 11.514,
      "end": 14.45,
      "safeEnd": true
    },
    {
      "text": "時とするとびっくりさせるような向日葵があったり",
      "start": 14.45,
      "end": 18.77,
      "safeEnd": true
    },
    {
      "text": "カンナが咲いていたりする。",
      "start": 18.77,
      "end": 20.88,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-street-v4-female.wav`
},
"male": {
  "passageId": "lemon-street-v4",
  "voice": "male",
  "duration": 20.76,
  "sampleRate": 48000,
  "sha256": "5dc5a23b82aeb5aa64b62ca3514cfd1c8e53e46c5e6fd2c824ef116d0bf7a47e",
  "cues": [
    {
      "text": "雨や風が蝕んで",
      "start": 0.0,
      "end": 1.904,
      "safeEnd": true
    },
    {
      "text": "やがて土に帰ってしまう、",
      "start": 1.904,
      "end": 4.352,
      "safeEnd": true
    },
    {
      "text": "と言ったような趣きのある街で、",
      "start": 4.352,
      "end": 7.132,
      "safeEnd": true
    },
    {
      "text": "土塀が崩れていたり",
      "start": 7.132,
      "end": 9.48,
      "safeEnd": true
    },
    {
      "text": "家並が傾きかかっていたり――",
      "start": 9.48,
      "end": 12.158,
      "safeEnd": true
    },
    {
      "text": "勢いのいいのは植物だけで、",
      "start": 12.158,
      "end": 14.806,
      "safeEnd": true
    },
    {
      "text": "時とするとびっくりさせるような向日葵があったり",
      "start": 14.806,
      "end": 18.518,
      "safeEnd": true
    },
    {
      "text": "カンナが咲いていたりする。",
      "start": 18.518,
      "end": 20.76,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-street-v4-male.wav`
}
},
"lemon-castle-v4": {
"female": {
  "passageId": "lemon-castle-v4",
  "voice": "female",
  "duration": 20.28,
  "sampleRate": 48000,
  "sha256": "71e183a2802216750f8e5674324fbd1c9313763117df67adae880cfcdacd7d2f",
  "cues": [
    {
      "text": "奇怪な幻想的な城が、",
      "start": 0.0,
      "end": 2.226,
      "safeEnd": true
    },
    {
      "text": "そのたびに赤くなったり青くなったりした。",
      "start": 2.226,
      "end": 5.844,
      "safeEnd": true
    },
    {
      "text": "やっとそれはでき上がった。",
      "start": 5.844,
      "end": 8.434,
      "safeEnd": true
    },
    {
      "text": "そして軽く跳りあがる心を制しながら、",
      "start": 8.434,
      "end": 12.336,
      "safeEnd": true
    },
    {
      "text": "その城壁の頂きに",
      "start": 12.336,
      "end": 14.408,
      "safeEnd": true
    },
    {
      "text": "恐る恐る檸檬を据えつけた。",
      "start": 14.408,
      "end": 17.458,
      "safeEnd": true
    },
    {
      "text": "そしてそれは上出来だった。",
      "start": 17.458,
      "end": 20.28,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-castle-v4-female.wav`
},
"male": {
  "passageId": "lemon-castle-v4",
  "voice": "male",
  "duration": 19.68,
  "sampleRate": 48000,
  "sha256": "7e1f517b98dc4b4bc60c14df057bdf91fcbc2cfd87f0c249ef6d6146c10c1b37",
  "cues": [
    {
      "text": "奇怪な幻想的な城が、",
      "start": 0.0,
      "end": 2.192,
      "safeEnd": true
    },
    {
      "text": "そのたびに赤くなったり青くなったりした。",
      "start": 2.192,
      "end": 5.7,
      "safeEnd": true
    },
    {
      "text": "やっとそれはでき上がった。",
      "start": 5.7,
      "end": 8.372,
      "safeEnd": true
    },
    {
      "text": "そして軽く跳りあがる心を制しながら、",
      "start": 8.372,
      "end": 11.818,
      "safeEnd": true
    },
    {
      "text": "その城壁の頂きに",
      "start": 11.818,
      "end": 13.958,
      "safeEnd": true
    },
    {
      "text": "恐る恐る檸檬を据えつけた。",
      "start": 13.958,
      "end": 16.906,
      "safeEnd": true
    },
    {
      "text": "そしてそれは上出来だった。",
      "start": 16.906,
      "end": 19.68,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-castle-v4-male.wav`
}
},
"lemon-glass-v4": {
"female": {
  "passageId": "lemon-glass-v4",
  "voice": "female",
  "duration": 26.2,
  "sampleRate": 48000,
  "sha256": "9cfe29de7da0c6dc9d4bbf899ab6bd868f29588c07c6868edb97e47df57de02e",
  "cues": [
    {
      "text": "あのびいどろの味ほど",
      "start": 0.0,
      "end": 2.054,
      "safeEnd": true
    },
    {
      "text": "幽かな涼しい味があるものか。",
      "start": 2.054,
      "end": 5.12,
      "safeEnd": true
    },
    {
      "text": "私は幼い時よくそれを口に入れては",
      "start": 5.12,
      "end": 9.47,
      "safeEnd": true
    },
    {
      "text": "父母に叱られたものだが、",
      "start": 9.47,
      "end": 11.656,
      "safeEnd": true
    },
    {
      "text": "その幼時のあまい記憶が",
      "start": 11.656,
      "end": 14.322,
      "safeEnd": true
    },
    {
      "text": "大きくなって落ち魄れた私に",
      "start": 14.322,
      "end": 16.812,
      "safeEnd": true
    },
    {
      "text": "蘇えってくる故だろうか、",
      "start": 16.812,
      "end": 18.916,
      "safeEnd": true
    },
    {
      "text": "まったくあの味には",
      "start": 18.916,
      "end": 20.768,
      "safeEnd": true
    },
    {
      "text": "幽かな爽やかななんとなく詩美と言ったような味覚が漂って来る。",
      "start": 20.768,
      "end": 26.2,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-glass-v4-female.wav`
},
"male": {
  "passageId": "lemon-glass-v4",
  "voice": "male",
  "duration": 25.72,
  "sampleRate": 48000,
  "sha256": "e54af42c3b563f6a4f50da7b34f45e850d0b87dd6ad7eb4ec43b6fd1fe052499",
  "cues": [
    {
      "text": "あのびいどろの味ほど",
      "start": 0.0,
      "end": 1.792,
      "safeEnd": true
    },
    {
      "text": "幽かな涼しい味があるものか。",
      "start": 1.792,
      "end": 4.764,
      "safeEnd": true
    },
    {
      "text": "私は幼い時よくそれを口に入れては",
      "start": 4.764,
      "end": 8.256,
      "safeEnd": true
    },
    {
      "text": "父母に叱られたものだが、",
      "start": 8.256,
      "end": 10.506,
      "safeEnd": true
    },
    {
      "text": "その幼時のあまい記憶が",
      "start": 10.506,
      "end": 13.288,
      "safeEnd": true
    },
    {
      "text": "大きくなって落ち魄れた私に",
      "start": 13.288,
      "end": 15.974,
      "safeEnd": true
    },
    {
      "text": "蘇えってくる故だろうか、",
      "start": 15.974,
      "end": 18.322,
      "safeEnd": true
    },
    {
      "text": "まったくあの味には",
      "start": 18.322,
      "end": 20.386,
      "safeEnd": true
    },
    {
      "text": "幽かな爽やかななんとなく詩美と言ったような味覚が漂って来る。",
      "start": 20.386,
      "end": 25.72,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/lemon-glass-v4-male.wav`
}
},
"galaxy-wages-v4": {
"female": {
  "passageId": "galaxy-wages-v4",
  "voice": "female",
  "duration": 21.52,
  "sampleRate": 48000,
  "sha256": "ede3b38eba9c9595dbb60c6d5e5f406f51a4ec94fb9d7f0c4bc7e04261bb945a",
  "cues": [
    {
      "text": "ジョバンニは俄かに顔いろがよくなって",
      "start": 0.0,
      "end": 2.688,
      "safeEnd": true
    },
    {
      "text": "威勢よくおじぎをすると",
      "start": 2.688,
      "end": 4.836,
      "safeEnd": true
    },
    {
      "text": "台の下に置いた鞄をもって",
      "start": 4.836,
      "end": 7.432,
      "safeEnd": true
    },
    {
      "text": "おもてへ飛びだしました。",
      "start": 7.432,
      "end": 9.658,
      "safeEnd": true
    },
    {
      "text": "それから元気よく口笛を吹きながら",
      "start": 9.658,
      "end": 13.19,
      "safeEnd": true
    },
    {
      "text": "パン屋へ寄って",
      "start": 13.19,
      "end": 14.682,
      "safeEnd": true
    },
    {
      "text": "パンの塊を一つと角砂糖を一袋買いますと",
      "start": 14.682,
      "end": 19.072,
      "safeEnd": true
    },
    {
      "text": "一目散に走りだしました。",
      "start": 19.072,
      "end": 21.52,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/galaxy-wages-v4-female.wav`
},
"male": {
  "passageId": "galaxy-wages-v4",
  "voice": "male",
  "duration": 21.2,
  "sampleRate": 48000,
  "sha256": "9aad90b49cfb35cfb8f279f06ca4d5d1970050e9411a657f665ccb1f09ea6fff",
  "cues": [
    {
      "text": "ジョバンニは俄かに顔いろがよくなって",
      "start": 0.0,
      "end": 3.112,
      "safeEnd": true
    },
    {
      "text": "威勢よくおじぎをすると",
      "start": 3.112,
      "end": 5.208,
      "safeEnd": true
    },
    {
      "text": "台の下に置いた鞄をもって",
      "start": 5.208,
      "end": 7.67,
      "safeEnd": true
    },
    {
      "text": "おもてへ飛びだしました。",
      "start": 7.67,
      "end": 9.774,
      "safeEnd": true
    },
    {
      "text": "それから元気よく口笛を吹きながら",
      "start": 9.774,
      "end": 12.76,
      "safeEnd": true
    },
    {
      "text": "パン屋へ寄って",
      "start": 12.76,
      "end": 14.186,
      "safeEnd": true
    },
    {
      "text": "パンの塊を一つと角砂糖を一袋買いますと",
      "start": 14.186,
      "end": 18.644,
      "safeEnd": true
    },
    {
      "text": "一目散に走りだしました。",
      "start": 18.644,
      "end": 21.2,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/galaxy-wages-v4-male.wav`
}
},
"galaxy-path-v4": {
"female": {
  "passageId": "galaxy-path-v4",
  "voice": "female",
  "duration": 19.36,
  "sampleRate": 48000,
  "sha256": "28356a25b94dd295e287dbc8ce4d54de46b70977c3eeffb41765a0c1d0b97197",
  "cues": [
    {
      "text": "ジョバンニは、",
      "start": 0.0,
      "end": 1.128,
      "safeEnd": true
    },
    {
      "text": "もう露の降りかかった小さな林のこみちを、",
      "start": 1.128,
      "end": 4.876,
      "safeEnd": true
    },
    {
      "text": "どんどんのぼって行きました。",
      "start": 4.876,
      "end": 7.256,
      "safeEnd": true
    },
    {
      "text": "まっくらな草や、",
      "start": 7.256,
      "end": 9.29,
      "safeEnd": true
    },
    {
      "text": "いろいろな形に見えるやぶのしげみの間を、",
      "start": 9.29,
      "end": 12.908,
      "safeEnd": true
    },
    {
      "text": "その小さなみちが、",
      "start": 12.908,
      "end": 14.77,
      "safeEnd": true
    },
    {
      "text": "一すじ白く星あかりに照らしだされてあったのです。",
      "start": 14.77,
      "end": 19.36,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/galaxy-path-v4-female.wav`
},
"male": {
  "passageId": "galaxy-path-v4",
  "voice": "male",
  "duration": 18.2,
  "sampleRate": 48000,
  "sha256": "175379bec1bea74be30841679ef36cd901aec744ce6e0be02566726dc7d75dcc",
  "cues": [
    {
      "text": "ジョバンニは、",
      "start": 0.0,
      "end": 1.094,
      "safeEnd": true
    },
    {
      "text": "もう露の降りかかった小さな林のこみちを、",
      "start": 1.094,
      "end": 4.674,
      "safeEnd": true
    },
    {
      "text": "どんどんのぼって行きました。",
      "start": 4.674,
      "end": 7.188,
      "safeEnd": true
    },
    {
      "text": "まっくらな草や、",
      "start": 7.188,
      "end": 9.172,
      "safeEnd": true
    },
    {
      "text": "いろいろな形に見えるやぶのしげみの間を、",
      "start": 9.172,
      "end": 12.394,
      "safeEnd": true
    },
    {
      "text": "その小さなみちが、",
      "start": 12.394,
      "end": 14.31,
      "safeEnd": true
    },
    {
      "text": "一すじ白く星あかりに照らしだされてあったのです。",
      "start": 14.31,
      "end": 18.2,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/galaxy-path-v4-male.wav`
}
},
"galaxy-platform-v4": {
"female": {
  "passageId": "galaxy-platform-v4",
  "voice": "female",
  "duration": 14.96,
  "sampleRate": 48000,
  "sha256": "ab5961284b964e73756c42f78ea06ae52d9654e9b8f1c3e1c29f9a33066088ef",
  "cues": [
    {
      "text": "さわやかな秋の時計の盤面には、",
      "start": 0.0,
      "end": 2.866,
      "safeEnd": true
    },
    {
      "text": "青く灼かれたはがねの二本の針が、",
      "start": 2.866,
      "end": 5.706,
      "safeEnd": true
    },
    {
      "text": "くっきり十一時を指しました。",
      "start": 5.706,
      "end": 8.5,
      "safeEnd": true
    },
    {
      "text": "みんなは、",
      "start": 8.5,
      "end": 9.79,
      "safeEnd": true
    },
    {
      "text": "一ぺんに下りて、",
      "start": 9.79,
      "end": 11.198,
      "safeEnd": true
    },
    {
      "text": "車室の中は",
      "start": 11.198,
      "end": 12.76,
      "safeEnd": true
    },
    {
      "text": "がらんとなってしまいました。",
      "start": 12.76,
      "end": 14.96,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/galaxy-platform-v4-female.wav`
},
"male": {
  "passageId": "galaxy-platform-v4",
  "voice": "male",
  "duration": 14.72,
  "sampleRate": 48000,
  "sha256": "310ce722f4541402a978cce1a991cf668fa6be502aff50551242e222f818ccd3",
  "cues": [
    {
      "text": "さわやかな秋の時計の盤面には、",
      "start": 0.0,
      "end": 2.636,
      "safeEnd": true
    },
    {
      "text": "青く灼かれたはがねの二本の針が、",
      "start": 2.636,
      "end": 5.596,
      "safeEnd": true
    },
    {
      "text": "くっきり十一時を指しました。",
      "start": 5.596,
      "end": 8.304,
      "safeEnd": true
    },
    {
      "text": "みんなは、",
      "start": 8.304,
      "end": 9.572,
      "safeEnd": true
    },
    {
      "text": "一ぺんに下りて、",
      "start": 9.572,
      "end": 11.006,
      "safeEnd": true
    },
    {
      "text": "車室の中は",
      "start": 11.006,
      "end": 12.548,
      "safeEnd": true
    },
    {
      "text": "がらんとなってしまいました。",
      "start": 12.548,
      "end": 14.72,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/galaxy-platform-v4-male.wav`
}
},
"galaxy-water-v4": {
"female": {
  "passageId": "galaxy-water-v4",
  "voice": "female",
  "duration": 12.44,
  "sampleRate": 48000,
  "sha256": "01fafc862be08489baefaff0abadf06d91f60fae44f96b70b9f0c6ba49353022",
  "cues": [
    {
      "text": "ジョバンニは、",
      "start": 0.0,
      "end": 1.036,
      "safeEnd": true
    },
    {
      "text": "走ってその渚に行って、",
      "start": 1.036,
      "end": 3.078,
      "safeEnd": true
    },
    {
      "text": "水に手をひたしました。",
      "start": 3.078,
      "end": 5.352,
      "safeEnd": true
    },
    {
      "text": "けれどもあやしいその銀河の水は、",
      "start": 5.352,
      "end": 8.976,
      "safeEnd": true
    },
    {
      "text": "水素よりも",
      "start": 8.976,
      "end": 10.288,
      "safeEnd": true
    },
    {
      "text": "もっとすきとおっていたのです。",
      "start": 10.288,
      "end": 12.44,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/galaxy-water-v4-female.wav`
},
"male": {
  "passageId": "galaxy-water-v4",
  "voice": "male",
  "duration": 12.24,
  "sampleRate": 48000,
  "sha256": "370a15fd2cbcb48ec13503d367585926392b11470f94b6cd4b5c2e08b81c2fb2",
  "cues": [
    {
      "text": "ジョバンニは、",
      "start": 0.0,
      "end": 1.028,
      "safeEnd": true
    },
    {
      "text": "走ってその渚に行って、",
      "start": 1.028,
      "end": 3.062,
      "safeEnd": true
    },
    {
      "text": "水に手をひたしました。",
      "start": 3.062,
      "end": 5.394,
      "safeEnd": true
    },
    {
      "text": "けれどもあやしいその銀河の水は、",
      "start": 5.394,
      "end": 8.406,
      "safeEnd": true
    },
    {
      "text": "水素よりも",
      "start": 8.406,
      "end": 9.804,
      "safeEnd": true
    },
    {
      "text": "もっとすきとおっていたのです。",
      "start": 9.804,
      "end": 12.24,
      "safeEnd": true
    }
  ]
,
  "url": `${NARRATION_ASSET_BASE_URL}/galaxy-water-v4-male.wav`
}
}
};
